/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.93
 * Generated at: 2024-08-11 07:00:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.home;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class homepage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1723226402286L));
    _jspx_dependants.put("jar:file:/C:/fullstack2/TREEP/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/TREEP/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<title>TREEP</title>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\r\n");
      out.write(" <main class=\"container-fluid\">\r\n");
      out.write("        <section class=\"main-banner\">\r\n");
      out.write("            <div class=\"main-banner-wrap\">\r\n");
      out.write("                <div class=\"main-banner-left\">\r\n");
      out.write("                    <h1>당신의 여행을 계획해보세요!</h1>\r\n");
      out.write("                    <button class=\"Treep-btn\" onclick=\"addSearch()\">TREEP 바로가기</button>\r\n");
      out.write("                    <div class=\"search-place\">\r\n");
      out.write("                        <div class=\"search-place-wrap\">\r\n");
      out.write("                            <i class=\"fa-solid fa-magnifying-glass\"></i>\r\n");
      out.write("                            <input class=\"search-place-nav\" type=\"text\" placeholder=\"집에 가고 싶다 ♥\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"search-place-box\">\r\n");
      out.write("                            <div class=\"search-place-scroll\">\r\n");
      out.write("                                <a href=\"#\" class=\"search-box-wrap\" data-bs-toggle=\"modal\"\r\n");
      out.write("                                    data-bs-target=\"#detail-modal\">\r\n");
      out.write("                                    <i class=\"fa-solid fa-location-dot\"></i>\r\n");
      out.write("                                    <div class=\"search-left\">\r\n");
      out.write("                                        <h5>제주</h5>\r\n");
      out.write("                                        <span>대한민국</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <a href=\"#\" class=\"search-box-wrap\" data-bs-toggle=\"modal\"\r\n");
      out.write("                                data-bs-target=\"#detail-modal\">\r\n");
      out.write("                                  <i class=\"fa-solid fa-location-dot\"></i>\r\n");
      out.write("                                    <div class=\"search-left\">\r\n");
      out.write("                                        <h5>코타키나발루</h5>\r\n");
      out.write("                                        <span>말레이시아</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </a>\r\n");
      out.write("                                <a href=\"#\" class=\"search-box-wrap\" data-bs-toggle=\"modal\"\r\n");
      out.write("                                    data-bs-target=\"#detail-modal\">\r\n");
      out.write("                                     <i class=\"fa-solid fa-location-dot\"></i>\r\n");
      out.write("                                    <div class=\"search-left\">\r\n");
      out.write("                                        <h5>나트랑</h5>\r\n");
      out.write("                                        <span>베트남</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    \r\n");
      out.write("                                </a>\r\n");
      out.write("                                <a href=\"#\" class=\"search-box-wrap\" data-bs-toggle=\"modal\"\r\n");
      out.write("                                data-bs-target=\"#detail-modal\">\r\n");
      out.write("                                 <i class=\"fa-solid fa-location-dot\"></i>\r\n");
      out.write("                                    <div class=\"search-left\">\r\n");
      out.write("                                        <h5>발리</h5>\r\n");
      out.write("                                        <span>인도네시아</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    \r\n");
      out.write("                                </a>\r\n");
      out.write("                                <a href=\"#\" class=\"search-box-wrap\" data-bs-toggle=\"modal\"\r\n");
      out.write("                                    data-bs-target=\"#detail-modal\">\r\n");
      out.write("                                     <i class=\"fa-solid fa-location-dot\"></i>\r\n");
      out.write("                                    <div class=\"search-left\">\r\n");
      out.write("                                        <h5>후쿠오카</h5>\r\n");
      out.write("                                        <span>일본</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    \r\n");
      out.write("                                </a>\r\n");
      out.write("                                <a href=\"#\" class=\"search-box-wrap\" data-bs-toggle=\"modal\"\r\n");
      out.write("                                data-bs-target=\"#detail-modal\">\r\n");
      out.write("                                 <i class=\"fa-solid fa-location-dot\"></i>\r\n");
      out.write("                                    <div class=\"search-left\">\r\n");
      out.write("                                        <h5>치앙마이</h5>\r\n");
      out.write("                                        <span>태국</span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                   \r\n");
      out.write("                                </a>\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"main-banner-right\">\r\n");
      out.write("\r\n");
      out.write("                    <img class=\"main-banner-plane\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/mainpage/plane1.png\" alt=\"\">\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"modal\" id=\"detail-modal\" tabindex=\"-1\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog modal-dialog-centered modal-xl\">\r\n");
      out.write("                <div class=\"modal-content container-fluid detail-modal-content\">\r\n");
      out.write("                    <div class=\"modal-header detail-modal-header\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"modal-body detail-modal-body row\">\r\n");
      out.write("                        <div class=\"detail-modal-left col-7\">\r\n");
      out.write("                            <span>OSAKA</span>\r\n");
      out.write("                            <h1>일본 오사카</h1>\r\n");
      out.write("                            <p>일본의 미식과 역사의 중심지, 도톤보리의 눈부신 불빛 아래, 전통적인 타코야키와 오코노미야키의 맛을 즐기세요. 오사카성에서는 일본의 고대 역사를 체험할 수 있습니다. 유니버셜 스튜디오 재팬에서는 환상적인 어트랙션을 경험할 수 있으며, 신세계의 츠텐카쿠 타워에서는 도시의 전경을 한 눈에 볼 수 있습니다. 오사카에서는 끝없는 모험과 발견이 기다립니다.</p>\r\n");
      out.write("                            <button class=\"make-plan-btn\">일정 만들기  <i class=\"fa-solid fa-chevron-right\"></i></button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"detail-modal-right col\">\r\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/mainpage/IMG_1.jpg\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("    \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <section class=\"main-place\">\r\n");
      out.write("            <h1>TREEP PICK!</h1>\r\n");
      out.write("            <nav class=\"main-place-nav\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a class=\"place-category category-selected\">전체</a></li>\r\n");
      out.write("                    <li><a class=\"place-category\">국내</a></li>\r\n");
      out.write("                    <li><a class=\"place-category\">해외</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </nav>\r\n");
      out.write("            <div style=\"width: 85%; margin: auto;\">\r\n");
      out.write("                <div class=\"card-wrap responsive recommend\">\r\n");
      out.write("                    <article class=\"main-card\">\r\n");
      out.write("                        <a href=\"\">\r\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/mainpage/IMG_1.jpg\" alt=\"\">\r\n");
      out.write("                            <div class=\"main-card-content\">\r\n");
      out.write("                                <h3>OSAKA</h3>\r\n");
      out.write("                                <span>일본 오사카</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </article>\r\n");
      out.write("                    <article class=\"main-card\">\r\n");
      out.write("                        <a href=\"\">\r\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/mainpage/IMG_2.jpg\" alt=\"\">\r\n");
      out.write("                            <div class=\"main-card-content\">\r\n");
      out.write("                                <h3>JEONJU</h3>\r\n");
      out.write("                                <span>대한민국 전주</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </article>\r\n");
      out.write("                    <article class=\"main-card\">\r\n");
      out.write("                        <a href=\"\">\r\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/mainpage/IMG_3.png\" alt=\"\">\r\n");
      out.write("                            <div class=\"main-card-content\">\r\n");
      out.write("                                <h3>Ha Long Bay</h3>\r\n");
      out.write("                                <span>베트남 하롱베이</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </article>\r\n");
      out.write("                    <article class=\"main-card\">\r\n");
      out.write("                        <a href=\"\">\r\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/mainpage/IMG_4.jpg\" alt=\"\">\r\n");
      out.write("                            <div class=\"main-card-content\">\r\n");
      out.write("                                <h3>KOTA KINABALU</h3>\r\n");
      out.write("                                <span>말레이시아 코타키나발루</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </article>\r\n");
      out.write("                    <article class=\"main-card\">\r\n");
      out.write("                        <a href=\"\">\r\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/mainpage/IMG_5.jpg\" alt=\"\">\r\n");
      out.write("                            <div class=\"main-card-content\">\r\n");
      out.write("                                <h3>BORACAY</h3>\r\n");
      out.write("                                <span>필리핀 보라카이</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </article>\r\n");
      out.write("                    <article class=\"main-card\">\r\n");
      out.write("                        <a href=\"\">\r\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/mainpage/IMG_1.jpg\" alt=\"\">\r\n");
      out.write("                            <div class=\"main-card-content\">\r\n");
      out.write("                                <h3>OSAKA</h3>\r\n");
      out.write("                                <span>일본 오사카1</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </article>\r\n");
      out.write("                    <article class=\"main-card\">\r\n");
      out.write("                        <a href=\"\">\r\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/mainpage/IMG_7.jpg\" alt=\"\">\r\n");
      out.write("                            <div class=\"main-card-content\">\r\n");
      out.write("                                <h3>SAPPORO</h3>\r\n");
      out.write("                                <span>일본 삿포로</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </article>\r\n");
      out.write("                    <article class=\"main-card\">\r\n");
      out.write("                        <a href=\"\">\r\n");
      out.write("                            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/mainpage/IMG_1.jpg\" alt=\"\">\r\n");
      out.write("                            <div class=\"main-card-content\">\r\n");
      out.write("                                <h3>OSAKA</h3>\r\n");
      out.write("                                <span>일본 오사카1</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </article>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"section-btn\">\r\n");
      out.write("                    <button class=\"recommend-prev-btn prev-btn\"><i class=\"fa-solid fa-caret-left\"></i></button>\r\n");
      out.write("                    <button class=\"recommend-next-btn next-btn\"><i class=\"fa-solid fa-caret-right\"></i></button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <section class=\"main-ad\">\r\n");
      out.write("            <div class=\"main-ad-header row\" data-aos=\"fade-right\" data-aos-duration=\"3500\" data-aos-delay=\"50\">\r\n");
      out.write("                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/mainpage/icon_1.png\" alt=\"\">\r\n");
      out.write("                <div class=\"ad-header-text\">\r\n");
      out.write("                    <h1>TREEP과 함께하는</h1>\r\n");
      out.write("                    <h1>최신 여행 정보</h1>\r\n");
      out.write("                    <h3>여행 계획을 세우기 막막할 때,</h3>\r\n");
      out.write("                    <h3>TREEP으로 일정을 공유하고 도움을 받아보세요.</h3>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"ad-together ad-wrap row\" data-aos=\"fade-up\" data-aos-duration=\"3500\" data-aos-delay=\"50\">\r\n");
      out.write("                <div class=\"ad-text col\">\r\n");
      out.write("                    <h2>여행 계획</h2>\r\n");
      out.write("                    <p>소중한 가족, 친구와 함께 여행을 계획하고</p>\r\n");
      out.write("                    <p>일정을 공유할 수 있어요.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"ad-together-bubble ad-bubble ad-right-bubble col-5\">\r\n");
      out.write("                    <i class=\"fa-solid fa-quote-left\"></i>\r\n");
      out.write("                    <p id=\"together-type\">TREEP에서 우리들의 여행 계획을 세워보자 !</p>\r\n");
      out.write("                    <i class=\"fa-solid fa-quote-right\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"ad-board ad-wrap row\" data-aos=\"fade-up\" data-aos-duration=\"3500\" data-aos-delay=\"50\">\r\n");
      out.write("                <div class=\"ad-board-bubble ad-bubble ad-left-bubble col-5\">\r\n");
      out.write("                    <i class=\"fa-solid fa-quote-left\"></i>\r\n");
      out.write("                    <p id=\"board-type\">지금 삿포로에 눈이 많이 오나요 ?</p>\r\n");
      out.write("                    <i class=\"fa-solid fa-quote-right\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"ad-text col\">\r\n");
      out.write("                    <h2>여행 정보 공유</h2>\r\n");
      out.write("                    <p>TREEP 회원들과 함께</p>\r\n");
      out.write("                    <p>여행지 최신 정보를 공유할 수 있어요.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"ad-join ad-wrap row\" data-aos=\"fade-up\" data-aos-duration=\"3500\" data-aos-delay=\"100\">\r\n");
      out.write("                <div class=\"ad-text col\">\r\n");
      out.write("                    <h2>여행 동행</h2>\r\n");
      out.write("                    <p>여행을 공유하고</p>\r\n");
      out.write("                    <p>동행 친구를 구해 일정을 함께 할 수 있어요.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"ad-join-bubble ad-bubble ad-right-bubble col-5\">\r\n");
      out.write("                    <i class=\"fa-solid fa-quote-left\"></i>\r\n");
      out.write("                    <p id=\"join-type\">광안리에서 조개구이 드실 분 계시나요 ?</p>\r\n");
      out.write("                    <i class=\"fa-solid fa-quote-right\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("        <section class=\"main-ad-banner\">\r\n");
      out.write("            <a href=\"\" class=\"ad-banner-wrap\">\r\n");
      out.write("                <div class=\"ad-banner-text\">\r\n");
      out.write("\r\n");
      out.write("                    <h2>🎉 여행 일정을 공유하고 스타벅스 기프티콘을 받자! 🎉</h2>\r\n");
      out.write("                    <p>여행을 준비하며 설렘 가득한 당신! ✈️🗺️ </p>\r\n");
      out.write("                    <p>이제 그 행복을 친구들과 나누고, 스타벅스 기프티콘까지 챙겨가세요! ☕️🎁</p>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"ad-banner-img\">\r\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/mainpage/starbucks.png\" alt=\"\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </a>\r\n");
      out.write("        </section>\r\n");
      out.write("\r\n");
      out.write("        <!-- <section class=\"main-review\">\r\n");
      out.write("            <div class=\"main-review-wrap\">\r\n");
      out.write("                <div class=\"review-banner\">\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"review-banner\">\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"review-banner\">\r\n");
      out.write(" \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section> -->\r\n");
      out.write("    </main>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/home/homepage.jsp(4,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path");
      // /WEB-INF/views/home/homepage.jsp(4,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/home/homepage.jsp(4,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
