/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.93
 * Generated at: 2024-08-11 14:00:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.signup;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class signup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1723226402286L));
    _jspx_dependants.put("jar:file:/C:/fullstack2/TREEP/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/TREEP/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("<main>\r\n");
      out.write("<div class=\"signup_space\">\r\n");
      out.write("        <div class=\"signup_space_title\">\r\n");
      out.write("            <p id=\"signup_space_title_main\">회원가입</p>\r\n");
      out.write("            <p id=\"signup_space_title_sub\">회원가입을 위한 정보를 입력하세요.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <form style=\"width: 100%;\" id=\"signup_form\" method=\"post\">\r\n");
      out.write("            <div class=\"input_area\">\r\n");
      out.write("                <label for=\"Inputname\" class=\"col-form-label\" id=\"input_text_common\">이름</label>\r\n");
      out.write("                <input type=\"text\" class=\"form-control form-control input_text_common mb-2\" id=\"Inputname\" name=\"member_name\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <label for=\"InputNICKname\" class=\"col-form-label\" id=\"input_text_common\">닉네임</label>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"mb-2\" id=\"signup_space_\">\r\n");
      out.write("                    <input type=\"text\" class=\"form-control form-control input_text_common mb-2\"  id=\"InputNICKname\" maxlength=\"10\"\r\n");
      out.write("                        aria-describedby=\"emailHelp\" name=\"member_nickname\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-auto\">\r\n");
      out.write("                        <button type=\"submit\" class=\"btn ms-2 button_orange mb-2\" id=\"submit_btn_forname\">확인</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <label for=\"Inputid\" class=\"col-form-label \" id=\"input_text_common\" >아이디</label>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"input_ID\" id=\"signup_space_\">\r\n");
      out.write("                    \r\n");
      out.write("                    <input type=\"text\" class=\"form-control form-control input_text_common mb-2\"  id=\"Inputid\" maxlength=\"20\"\r\n");
      out.write("                        aria-describedby=\"emailHelp\" name=\"member_id\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-auto\">\r\n");
      out.write("                        <button type=\"submit\" class=\"btn ms-2 button_orange mb-2\" id=\"submit_btn_forID\" >확인</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"input_area\">\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("\r\n");
      out.write("                <label for=\"InputPassword\" class=\"col-form-label\" id=\"input_text_common\">비밀번호</label>\r\n");
      out.write("                <input type=\"password\" class=\"form-control form-control input_text_common mb-2\"  name=\"member_pw\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <label for=\"InputPassword\" class=\"col-form-label\" id=\"input_text_common\">이메일</label>\r\n");
      out.write("                <input type=\"text\" class=\"form-control form-control input_text_common mb-2\" name=\"member_email\">\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <label for=\"InputGender\" class=\"col-form-label\" id=\"input_text_common\">성별</label>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"memberGender_input\">\r\n");
      out.write("                <div class=\"signup_gender\">\r\n");
      out.write("                <input type=\"radio\" class=\"gender_check\"   id=\"male\"  checked name=\"member_gender\" value='M'>\r\n");
      out.write("                <label class=\"gender_check_male\" for=\"male\">남성</label>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"signup_gender\">\r\n");
      out.write("                <input type=\"radio\" class=\"gender_check\"   id=\"female\"  name=\"member_gender\" value='F'>\r\n");
      out.write("                <label class=\"gender_check_female\" for=\"female\">여성</label>\r\n");
      out.write("            </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div>\r\n");
      out.write("                <label for=\"InputPhone\" class=\"col-form-label\" id=\"input_text_common\">전화번호</label>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"memberPhone_input\">\r\n");
      out.write("                <div class=\"memberPhoneNumber_input\">\r\n");
      out.write("                    <input type=\"tel\" class=\"form-control form-control-lg input_text_common mb-2\" id=\"InputPhone\" name=\"member_phone\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div>\r\n");
      out.write("                <label for=\"InputBirth\" class=\"col-form-label\" id=\"input_text_common\">생년월일</label>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"InputBirth_div\">\r\n");
      out.write("                <input type=\"date\" name=\"member_birth\" class=\"p-4 memberBirthDate\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"input_area\">\r\n");
      out.write("            <button type=\"submit\" class=\"btn button_orange signup_btn\" id=\"signup_btn\">다음</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</main>\r\n");
      out.write("<script>\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("	$(\".signup_btn\").click(function(){\r\n");
      out.write("	\r\n");
      out.write("	$(\"#signup_form\").attr(\"action\", \"/sns/signupinfo\");\r\n");
      out.write("	$(\"#signup_form\").submit();\r\n");
      out.write("		\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
